#!/usr/bin/env bash
#loops 10 best schools but repolace number 4 and 8 with good/badluck
c=1
while [ $c -le 100 ]
do
    if [ $((c%3)) = 0 ]
    then
	printf "Fizz"
    fi
    if [ $((c%5)) = 0 ]
    then
	printf "Buzz"
    fi
    if [ $((c%3)) != 0 ] && [ $((c%5)) != 0 ]
    then
	printf "%s"$c
    fi
    echo ""
    ((c++))
done
      
