#!/usr/bin/env bash
# ifs.sh
#prints a story or each entry in passwd
IFS=":"
while read -r name passwd usrID grpID comment homedir option
do
    printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n""$1" "$name" "$grpID" "$homedir" "$option" "$usrID" "$passwd" "$comment"
done < /etc/passwd
printf ""
