#!/usr/bin/env bash
#loops 10 best schools but repolace number 4 and 8 with good/badluck
c=1
while [ $c -le 10 ]
do
    if [ $c = 4 ]
    then
	echo "bad luck"
    elif [ $c = 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    ((c++))
done
      
