#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

touch /var/run/myscript.pid
pgrep -f "10-process_and_pid_file" > /var/run/myscript.pid 


trap 'rm -f /var/run/myscript.pid; exit 1' SIGQUIT
trap 'echo Y U no love me?!' SIGINT
trap 'echo I hate the kill command;rm -f /var/run/myscript.pid; exit 1' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
